###
POST http://localhost:5000/category/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM2MDEzOSwianRpIjoiYjUyN2NiOTgtYjlkZi00ZjkxLTk5YjQtYWU5ZWFmY2RkOGI3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM2MDEzOSwiY3NyZiI6ImU4ZDhhYzAwLTIzMGQtNDlkNS1iYzJhLTAxZDZjNWQwMDRkNiIsImV4cCI6MTczMDM2MzczOX0.EAD0cuflPuCdR5kCRbyE9vkOuMpyJuMhEpByviO587k

{
  "user_id" : "27daa87f-60fc-4ff0-a8a5-ddc36b468f41",
  "name" : "shopping",
  "budget" : 50
}

### List Category
GET http://localhost:5000/category/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NDUzNSwianRpIjoiMjg0MzMxMjEtMDdmMi00ZDIwLTg5MzEtMmE4NmIxNzkyNzIzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NDUzNSwiY3NyZiI6ImM5MzVmNGYwLTk2YzQtNDdkNS04OThiLWYzYzhhZmFlZTczOCIsImV4cCI6MTczMDM3ODEzNX0.mtGKSCzfkOCSzJ9fYqjaQVv-9WRATD6UBXZpivzFzqk

### Delete Cateogry
DELETE http://localhost:5000/category/delete/8bd93362-307b-443b-b490-91a5c2ce4179
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM2MDEzOSwianRpIjoiYjUyN2NiOTgtYjlkZi00ZjkxLTk5YjQtYWU5ZWFmY2RkOGI3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM2MDEzOSwiY3NyZiI6ImU4ZDhhYzAwLTIzMGQtNDlkNS1iYzJhLTAxZDZjNWQwMDRkNiIsImV4cCI6MTczMDM2MzczOX0.EAD0cuflPuCdR5kCRbyE9vkOuMpyJuMhEpByviO587k
