### Add Expense
POST http://localhost:5000/expenses/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NTA3OCwianRpIjoiZWUwNDY1M2QtMTgzMC00MThhLTk1NWYtNDBhYzM2MDYzNTg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NTA3OCwiY3NyZiI6ImIyM2NjM2QxLTYwZTctNDI0MS05N2VkLWMyODA3NTgwNGRmNiIsImV4cCI6MTczMDM3ODY3OH0.-WJoYQ4PtooUNYK9b1BfXYurn4lEm3cs1e73wm-YDBo

{
  "category_id": "8bd93362-307b-443b-b490-91a5c2ce4179",
  "amount": "10.20",
  "description": "Halloween Costume",
  "date": "2024-10-30 23:45:00+00:00"
}

### List all Expense
GET http://localhost:5000/expenses/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NTA3OCwianRpIjoiZWUwNDY1M2QtMTgzMC00MThhLTk1NWYtNDBhYzM2MDYzNTg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NTA3OCwiY3NyZiI6ImIyM2NjM2QxLTYwZTctNDI0MS05N2VkLWMyODA3NTgwNGRmNiIsImV4cCI6MTczMDM3ODY3OH0.-WJoYQ4PtooUNYK9b1BfXYurn4lEm3cs1e73wm-YDBo


### # sum all Expense
GET http://localhost:5000/expenses/count/8bd93362-307b-443b-b490-91a5c2ce4179
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NTA3OCwianRpIjoiZWUwNDY1M2QtMTgzMC00MThhLTk1NWYtNDBhYzM2MDYzNTg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NTA3OCwiY3NyZiI6ImIyM2NjM2QxLTYwZTctNDI0MS05N2VkLWMyODA3NTgwNGRmNiIsImV4cCI6MTczMDM3ODY3OH0.-WJoYQ4PtooUNYK9b1BfXYurn4lEm3cs1e73wm-YDBo


### update Expense
PUT http://localhost:5000/expenses/update/48ab5ae9-9c12-4708-9d6d-ad6bfc999838
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NTA3OCwianRpIjoiZWUwNDY1M2QtMTgzMC00MThhLTk1NWYtNDBhYzM2MDYzNTg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NTA3OCwiY3NyZiI6ImIyM2NjM2QxLTYwZTctNDI0MS05N2VkLWMyODA3NTgwNGRmNiIsImV4cCI6MTczMDM3ODY3OH0.-WJoYQ4PtooUNYK9b1BfXYurn4lEm3cs1e73wm-YDBo
Content-Type: application/json

{
  "category_id": "8bd93362-307b-443b-b490-91a5c2ce4179",
  "amount": "11",
  "description": "Halloween Costume",
  "date": "2024-10-30 23:45:00+00:00"
}

### Delete Expense
DELETE http://localhost:5000/expenses/delete/48ab5ae9-9c12-4708-9d6d-ad6bfc999838
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMDM3NTA3OCwianRpIjoiZWUwNDY1M2QtMTgzMC00MThhLTk1NWYtNDBhYzM2MDYzNTg2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI3ZGFhODdmLTYwZmMtNGZmMC1hOGE1LWRkYzM2YjQ2OGY0MSIsIm5iZiI6MTczMDM3NTA3OCwiY3NyZiI6ImIyM2NjM2QxLTYwZTctNDI0MS05N2VkLWMyODA3NTgwNGRmNiIsImV4cCI6MTczMDM3ODY3OH0.-WJoYQ4PtooUNYK9b1BfXYurn4lEm3cs1e73wm-YDBo
